// export const GET_EMPS_LIST = 'forEmpsData/GET_EMPS_LIST'
export const SET_EMPS_LIST = 'forEmpsData/SET_EMPS_LIST'

export const SET_TOTAL_EMPS_COUNT = 'forEmpsData/SET_TOTAL_EMPS_COUNT'

export const SET_IS_LOADING_EMPS_LIST = 'forEmpsData/SET_IS_LOADING_EMPS_LIST'

export const SET_CURRENT_PAGE = 'forEmpsData/SET_CURRENT_PAGE'
export const SET_SEARCH_REQUEST = 'forEmpsData/SET_SEARCH_REQUEST'
export const SET_CURRENT_COMPANY = 'forEmpsData/SET_CURRENT_COMPANY'

export const GET_EMPLOYEE_IN_MODAL = 'forEmpsData/GET_EMPLOYEE_IN_MODAL'
export const SET_EMPLOYEE_IN_MODAL = 'forEmpsData/SET_EMPLOYEE_IN_MODAL'
export const SET_IS_LOADING_EMPLOYEE_MODAL_DATA = 'forEmpsData/SET_IS_LOADING_EMPLOYEE_MODAL_DATA'