export const SET_ERR_ON_LOAD_EMPLOYEES_LIST = 'forErrorsData/SET_ERR_ON_LOAD_EMPLOYEES_LIST'
export const SET_ERR_ON_LOAD_EMPLOYEE_IN_MODAL = 'forErrorsData/SET_ERR_ON_LOAD_EMPLOYEE_IN_MODAL'

export const SET_ERR_ON_LOGIN = 'forErrorsData/SET_ERR_ON_LOGIN'

export const SET_ERR_ON_LOAD_ADMIN_EMPS_LIST = 'forErrorsData/SET_ERR_ON_LOAD_ADMIN_EMPS_LIST'

export const ADD_ERR_ON_DELETE_EMPLOYEE = 'forErrorsData/ADD_ERR_ON_DELETE_EMPLOYEE'

export const SET_ERR_ON_GET_INITIAL_DATA_FOR_UPDATE_PAGE = 'forErrorsData/SET_ERR_ON_GET_INITIAL_DATA_FOR_UPDATE_PAGE'

export const SET_ERR_ON_GET_INITIAL_PORTION_FOR_MODAL = 'forErrorsData/SET_ERR_ON_GET_INITIAL_PORTION_FOR_MODAL'
export const SET_ERR_ON_EXPAND_PORTION_FOR_MODAL = 'forErrorsData/SET_ERR_ON_EXPAND_PORTION_FOR_MODAL'

export const SET_ERR_ON_UPDATE_EMPLOYEE = 'forErrorsData/SET_ERR_ON_UPDATE_EMPLOYEE'

export const SET_ERR_ON_CREATE_EMPLOYEE = 'forErrorsData/SET_ERR_ON_CREATE_EMPLOYEE'

export const SET_ERR_ON_GET_COMPANIES_LIST = 'forErrorsData/SET_ERR_ON_GET_COMPANIES_LIST'
export const SET_ERR_ON_CREATE_COMPANY = 'forErrorsData/SET_ERR_ON_CREATE_COMPANY'
export const ADD_ERR_ON_DELETE_UPDATE_COMPANY = 'forErrorsData/ADD_ERR_ON_DELETE_UPDATE_COMPANY'