export const GET_COMPANIES_LIST = 'forCompaniesData/GET_COMPANIES_LIST'
export const SET_COMPANIES_LIST = 'forCompaniesData/SET_COMPANIES_LIST'
export const SET_IS_LOADING_COMPANIES_LIST = 'forCompaniesData/SET_IS_LOADING_COMPANIES_LIST'

export const SET_IS_COMPANIES_LIST_REQUESTED = 'forCompaniesData/SET_IS_COMPANIES_LIST_REQUESTED'

export const CREATE_COMPANY = 'forCompaniesData/CREATE_COMPANY'
export const SET_IS_IN_PROGRESS_CREATE_COMPANY = 'forCompaniesData/SET_IS_IN_PROGRESS_CREATE_COMPANY'
export const ADD_NEW_COMPANY_IN_STORE = 'forCompaniesData/ADD_NEW_COMPANY_IN_STORE'

export const DELETE_COMPANY = 'forCompaniesData/DELETE_COMPANY'
export const REMOVE_COMPANY_FROM_STORE = 'forCompaniesData/REMOVE_COMPANY_FROM_STORE'
export const SET_IS_IN_PROGRESS_DELETE_COMPANY = 'forCompaniesData/SET_IS_IN_PROGRESS_DELETE_COMPANY'


export const UPDATE_COMPANY = 'forCompaniesData/UPDATE_COMPANY'
export const UPDATE_COMPANY_DATA_IN_STORE = 'forCompaniesData/UPDATE_COMPANY_DATA_IN_STORE'
export const SET_IS_IN_PROGRESS_UPDATE_COMPANY = 'forCompaniesData/SET_IS_IN_PROGRESS_UPDATE_COMPANY'