export const SET_EMPS_LIST = 'forAdminData/SET_EMPS_LIST'

export const SET_TOTAL_EMPS_COUNT = 'forAdminData/SET_TOTAL_EMPS_COUNT'

export const SET_IS_LOADING_EMPS_LIST = 'forAdminData/SET_IS_LOADING_EMPS_LIST'

export const SET_CURRENT_PAGE = 'forAdminData/SET_CURRENT_PAGE'
export const SET_SEARCH_REQUEST = 'forAdminData/SET_SEARCH_REQUEST'
export const SET_CURRENT_COMPANY_IDX_PAGE = 'forAdminData/SET_CURRENT_COMPANY_IDX_PAGE'

export const DELETE_EMPLOYEE = 'forAdminData/DELETE_EMPLOYEE'
export const SET_IS_IN_PROGRESS_DELETE_EMPLOYEE = 'forAdminData/SET_IS_IN_PROGRESS_DELETE_EMPLOYEE'
export const ADD_EMP_TO_DELETED = 'forAdminData/ADD_EMP_TO_DELETED'

export const GET_EMPLOYEE_DATA_FOR_UPDATE = 'forAdminData/GET_EMPLOYEE_DATA_FOR_UPDATE'
export const SET_EMPLOYEE_DATA_FOR_UPDATE = 'forAdminData/SET_EMPLOYEE_DATA_FOR_UPDATE'
export const IS_IN_PROGRESS_GET_EMP_DATA_FOR_UPDATE = 'forAdminData/IS_IN_PROGRESS_GET_EMP_DATA_FOR_UPDATE'

export const SET_CURRENT_PAGE_FOR_MODAL = 'forAdminData/SET_CURRENT_PAGE_FOR_MODAL'
export const SET_SEARCH_REQUEST_FOR_MODAL = 'forAdminData/SET_SEARCH_REQUEST_FOR_MODAL'

export const GET_INITIAL_PORTION_EMPLOYEES_FOR_MODAL = 'forAdminData/GET_INITIAL_PORTION_EMPLOYEES_FOR_MODAL'
export const SET_INITIAL_PORTION_EMPLOYEES_FOR_MODAL = 'forAdminData/SET_PORTION_EMPLOYEES_FOR_MODAL'
export const SET_TOTAL_COUNT_EMPLOYEES_FOR_MODAL = 'forAdminData/SET_TOTAL_COUNT_EMPLOYEES_FOR_MODAL'

export const GET_EXPAND_PORTION_EMPLOYEES_FOR_MODAL = 'forAdminData/GET_EXPAND_PORTION_EMPLOYEES_FOR_MODAL'
export const EXPAND_PORTION_EMPLOYEES_FOR_MODAL = 'forAdminData/EXPAND_PORTION_EMPLOYEES_FOR_MODAL'

export const SET_IS_LOADING_INITIAL_PORTION_FOR_MODAl = 'forAdminData/SET_IS_LOADING_INITIAL_PORTION_FOR_MODAl'
export const SET_IS_LOADING_EXPAND_PORTION_FOR_MODAl = 'forAdminData/SET_IS_LOADING_EXPAND_PORTION_FOR_MODAl'

export const UPDATE_EMPLOYEE = 'forAdminData/UPDATE_EMPLOYEE'
export const SET_IS_IN_PROGRESS_UPDATE_EMPLOYEE = 'forAdminData/SET_IS_IN_PROGRESS_UPDATE_EMPLOYEE'

export const CREATE_EMPLOYEE = 'forAdminData/CREATE_EMPLOYEE'
export const SET_INITIAL_EMPLOYEE_DATA_FOR_CREATE_PAGE = 'forAdminData/SET_INITIAL_EMPLOYEE_DATA_FOR_CREATE_PAGE'
export const SET_IS_IN_PROGRESS_CREATE_EMPLOYEE = 'forAdminData/SET_IS_IN_PROGRESS_CREATE_EMPLOYEE'

